name: Build/Test

on:
  push:
    paths:
      - '**.cs'
      - '**.yml'
  pull_request:
    paths:
      - '**.cs'
      - '**.yml'
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Set MemberApiKey
      id: setmemberapikey
      shell: bash
      run: |
        if [ "$MEMBER_API_KEY" != "" ]; then
          dotnet user-secrets set "MemberApiKey" "$MEMBER_API_KEY" --project src/jiraF.Member.API/
        else
          dotnet user-secrets set "MemberApiKey" "12345testApiKey" --project src/jiraF.Member.API/
        fi
      env:
        MEMBER_API_KEY: ${{ secrets.MEMBER_API_KEY }}
    - name: Set RABBITMQ_DEFAULT_USER
      id: setrabbituser
      shell: bash
      run: |
        if [ "$RABBITMQ_DEFAULT_USER" != "" ]; then
          dotnet user-secrets set "RABBITMQ_DEFAULT_USER" "$RABBITMQ_DEFAULT_USER" --project src/jiraF.Member.API/
        else
          dotnet user-secrets set "RABBITMQ_DEFAULT_USER" "CI_TESTS" --project src/jiraF.Member.API/
        fi
      env:
        RABBITMQ_DEFAULT_USER: ${{ secrets.RABBITMQ_DEFAULT_USER }}
    - name: Set RABBITMQ_DEFAULT_PASS
      id: setrabbitpass
      shell: bash
      run: |
        if [ "$RABBITMQ_DEFAULT_PASS" != "" ]; then
          dotnet user-secrets set "RABBITMQ_DEFAULT_PASS" "$RABBITMQ_DEFAULT_PASS" --project src/jiraF.Member.API/
        else
          dotnet user-secrets set "RABBITMQ_DEFAULT_PASS" "CI_TESTS" --project src/jiraF.Member.API/
        fi
      env:
        RABBITMQ_DEFAULT_PASS: ${{ secrets.RABBITMQ_DEFAULT_PASS }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal